# 此工作流将使用node运行测试，然后在创建发行版时将软件包发布到GitHub软件包
# 有关更多信息，请参见: https:// 帮助。github。com/操作/语言和框架指南/发布-nodejs包

名称: 节点。js包

上:
释放:
类型: [创建]

工作:
构建:
运行: ubuntu-最新
步骤:
-用途: 操作/结帐 @ v2
-用途: 操作/设置-节点 @ v2
使用:
节点-版本: 12
-运行: npm ci
-运行: npm测试

发布-npm:
需求: 构建
运行: ubuntu-最新
步骤:
-用途: 操作/结帐 @ v2
-用途: 操作/设置-节点 @ v2
使用:
节点-版本: 12
注册表-url: https:// 注册表npmjs。组织/
-运行: npm ci
-运行: npm发布
环境:
NODE_AUTH_TOKEN: ${{ 秘密。npm_token}}

发布-gpr:
需求: 构建
运行: ubuntu-最新
权限:
内容: 阅读
包: 写
步骤:
-用途: 操作/结帐 @ v2
-用途: 操作/设置-节点 @ v2
使用:
节点-版本: 12
注册表-url: https:// npmpkg。github。com/
-运行: npm ci
-运行: npm发布
环境:
NODE_AUTH_TOKEN: ${{ 秘密。GITHUB_TOKEN}}
